In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("forest_fire_scaled.csv")
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Temp_Humidity,Temp_Humidity_Ratio,Heat_Index,Fire_Risk,Fire_Risk_Label,Fire_Risk_Encoded
0,1,6,2012,-0.870655,-0.340673,0.893277,-0.381657,-0.847927,-0.912120,-0.879401,-0.830356,-0.936012,-0.880159,NaN,0.845358,0.171464,-0.910048,Low,0,0
1,2,6,2012,-0.870655,-0.070359,-0.888877,0.268642,-0.938709,-0.855520,-0.879401,-0.902720,-0.900798,-0.893626,NaN,0.635492,0.479718,-0.898174,Low,0,0
2,3,6,2012,-1.699254,1.348788,2.319000,6.171355,-2.146802,-0.984891,-0.889913,-1.071571,-0.985310,-0.934029,NaN,-1.462895,0.051677,-1.687685,Low,0,0
3,4,6,2012,-1.975454,1.821837,-0.888877,0.868918,-3.438694,-1.081920,-0.894117,-1.143935,-1.055737,-0.947497,NaN,-2.628391,0.057187,-1.950855,Low,0,0
4,5,6,2012,-1.423054,1.010896,0.180416,-0.381657,-0.910776,-0.944463,-0.740651,-0.854477,-0.900798,-0.880159,NaN,-0.701925,0.047034,-1.418578,Low,0,0


In [3]:
df.shape

(243, 20)

In [4]:
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Temp_Humidity',
       'Temp_Humidity_Ratio', 'Heat_Index', 'Fire_Risk', 'Fire_Risk_Label',
       'Fire_Risk_Encoded'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   day                  243 non-null    int64  
 1   month                243 non-null    int64  
 2   year                 243 non-null    int64  
 3   Temperature          243 non-null    float64
 4   RH                   243 non-null    float64
 5   Ws                   243 non-null    float64
 6   Rain                 243 non-null    float64
 7   FFMC                 243 non-null    float64
 8   DMC                  243 non-null    float64
 9   DC                   243 non-null    float64
 10  ISI                  243 non-null    float64
 11  BUI                  243 non-null    float64
 12  FWI                  243 non-null    float64
 13  Classes              0 non-null      float64
 14  Temp_Humidity        243 non-null    float64
 15  Temp_Humidity_Ratio  243 non-null    flo

In [6]:
df.columns = df.columns.str.strip()
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Temp_Humidity',
       'Temp_Humidity_Ratio', 'Heat_Index', 'Fire_Risk', 'Fire_Risk_Label',
       'Fire_Risk_Encoded'],
      dtype='object')

In [7]:
df['Classes'].unique()

array([nan])

In [8]:
df.isnull().sum()

day                      0
month                    0
year                     0
Temperature              0
RH                       0
Ws                       0
Rain                     0
FFMC                     0
DMC                      0
DC                       0
ISI                      0
BUI                      0
FWI                      0
Classes                243
Temp_Humidity            0
Temp_Humidity_Ratio      0
Heat_Index               0
Fire_Risk                0
Fire_Risk_Label          0
Fire_Risk_Encoded        0
dtype: int64

In [9]:
df = df[df['Classes'] != 'Classes']

In [10]:
df['Classes'].unique()

array([nan])

In [11]:
df.isnull().sum()

day                      0
month                    0
year                     0
Temperature              0
RH                       0
Ws                       0
Rain                     0
FFMC                     0
DMC                      0
DC                       0
ISI                      0
BUI                      0
FWI                      0
Classes                243
Temp_Humidity            0
Temp_Humidity_Ratio      0
Heat_Index               0
Fire_Risk                0
Fire_Risk_Label          0
Fire_Risk_Encoded        0
dtype: int64

In [12]:
df['Classes'] = df['Classes'].map({'not fire':0, 'fire':1})

In [13]:
for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = pd.to_numeric(df[column], errors='coerce')

In [14]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   day                  243 non-null    int64  
 1   month                243 non-null    int64  
 2   year                 243 non-null    int64  
 3   Temperature          243 non-null    float64
 4   RH                   243 non-null    float64
 5   Ws                   243 non-null    float64
 6   Rain                 243 non-null    float64
 7   FFMC                 243 non-null    float64
 8   DMC                  243 non-null    float64
 9   DC                   243 non-null    float64
 10  ISI                  243 non-null    float64
 11  BUI                  243 non-null    float64
 12  FWI                  243 non-null    float64
 13  Classes              0 non-null      float64
 14  Temp_Humidity        243 non-null    float64
 15  Temp_Humidity_Ratio  243 non-null    flo

(243, 20)

In [15]:
df.to_csv("forest_fire_scaled.csv", index=False)

In [16]:
import numpy as np

# to make sure FWI is numeric
raw_fwi = df['FWI']

conditions = [
    (raw_fwi < -0.54),
    (raw_fwi >= -0.54) & (raw_fwi < 0.85),
    (raw_fwi >= 0.85)
]

risk_levels = ['Low', 'Moderate', 'Severe']

df['Fire_Risk'] = np.select(conditions, risk_levels, default='Low')

In [17]:
print(df['Fire_Risk'].value_counts())

Fire_Risk
Low         104
Moderate     90
Severe       49
Name: count, dtype: int64


In [18]:
df['Fire_Risk_Label'] = df['Fire_Risk'].map({
    'Low': 0,
    'Moderate': 1,
    'Severe': 2
})

In [19]:
print(df[['FWI','Fire_Risk','Fire_Risk_Label']])

          FWI Fire_Risk  Fire_Risk_Label
0   -0.880159       Low                0
1   -0.893626       Low                0
2   -0.934029       Low                0
3   -0.947497       Low                0
4   -0.880159       Low                0
..        ...       ...              ...
238 -0.072104  Moderate                1
239 -0.947497       Low                0
240 -0.920561       Low                0
241 -0.853223       Low                0
242 -0.880159       Low                0

[243 rows x 3 columns]


In [20]:
print(df['Fire_Risk'].value_counts())

Fire_Risk
Low         104
Moderate     90
Severe       49
Name: count, dtype: int64


In [21]:
df.to_csv("algerian_forest_fire_with_features.csv", index=False)

In [22]:
df['Temp_Humidity'] = df['Temperature'] * df['RH']

In [23]:
df['Temp_Humidity_Ratio'] = df['Temperature'] / df['RH']

In [24]:
df['Heat_Index'] = 0.5 * (df['Temperature'] + 61.0 + ((df['Temperature']-68.0)*1.2) + (df['RH']*0.094))

In [25]:
df[['Temperature','RH','Temp_Humidity','Temp_Humidity_Ratio','Heat_Index']]

,Temperature,RH,Temp_Humidity,Temp_Humidity_Ratio,Heat_Index
0,-0.870655,-0.340673,0.296609,2.555689,-11.273732
1,-0.870655,-0.070359,0.061259,12.374382,-11.261027
2,-1.699254,1.348788,-2.291934,-1.259838,-12.105787
3,-1.975454,1.821837,-3.598955,-1.084320,-12.387373
4,-1.423054,1.010896,-1.438560,-1.407716,-11.817848
...,...,...,...,...,...
238,-0.594455,0.199954,-0.118864,-2.972953,-10.944502
239,-1.146855,1.686680,-1.934377,-0.679948,-11.482266
240,-1.423054,1.686680,-2.400238,-0.843701,-11.786086
241,-2.251654,-0.543409,1.223568,4.143575,-12.802360


In [26]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["Fire_Risk_Encoded"] = le.fit_transform(df["Fire_Risk"])

print("Label Encoding mapping:")
for cls, val in zip(le.classes_, range(len(le.classes_))):
    print(f"  {cls} -> {val}")
print()
print(df[["Fire_Risk", "Fire_Risk_Encoded"]].drop_duplicates().sort_values("Fire_Risk_Encoded"))

Label Encoding mapping:
  Low -> 0
  Moderate -> 1
  Severe -> 2

   Fire_Risk  Fire_Risk_Encoded
0        Low                  0
6   Moderate                  1
26    Severe                  2


In [27]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

cols_to_scale = ["Temperature", "RH", "Ws", "Rain", "FFMC", "DMC", "DC",
                 "ISI", "BUI", "FWI", "Temp_Humidity", "Temp_Humidity_Ratio", "Heat_Index"]

# Standard Scaling (mean=0, std=1)
scaler = StandardScaler()
df_scaled = df.copy()
df_scaled[cols_to_scale] = scaler.fit_transform(df[cols_to_scale])

print("Standard Scaled - first 5 rows:")
print(df_scaled[cols_to_scale].head())
print()
print("Mean after scaling (should be ~0):")
print(df_scaled[cols_to_scale].mean().round(4))

Standard Scaled - first 5 rows:
   Temperature        RH        Ws      Rain      FFMC       DMC        DC  \
0    -0.870655 -0.340673  0.893277 -0.381657 -0.847927 -0.912120 -0.879401   
1    -0.870655 -0.070359 -0.888877  0.268642 -0.938709 -0.855520 -0.879401   
2    -1.699254  1.348788  2.319000  6.171355 -2.146802 -0.984891 -0.889913   
3    -1.975454  1.821837 -0.888877  0.868918 -3.438694 -1.081920 -0.894117   
4    -1.423054  1.010896  0.180416 -0.381657 -0.910776 -0.944463 -0.740651   

        ISI       BUI       FWI  Temp_Humidity  Temp_Humidity_Ratio  \
0 -0.830356 -0.936012 -0.880159       0.845358             0.171464   
1 -0.902720 -0.900798 -0.893626       0.635492             0.479718   
2 -1.071571 -0.985310 -0.934029      -1.462895             0.051677   
3 -1.143935 -1.055737 -0.947497      -2.628391             0.057187   
4 -0.854477 -0.900798 -0.880159      -0.701925             0.047034   

   Heat_Index  
0   -0.910048  
1   -0.898174  
2   -1.687685  
3   -1.9

In [28]:
mm_scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[cols_to_scale] = mm_scaler.fit_transform(df[cols_to_scale])

print("MinMax Scaled - first 5 rows:")
print(df_minmax[cols_to_scale].head())
print()
print("Min values (should be 0):")
print(df_minmax[cols_to_scale].min())
print("Max values (should be 1):")
print(df_minmax[cols_to_scale].max())

MinMax Scaled - first 5 rows:
   Temperature        RH        Ws      Rain      FFMC       DMC        DC  \
0         0.35  0.521739  0.521739  0.000000  0.550445  0.041411  0.003279   
1         0.35  0.579710  0.304348  0.077381  0.531157  0.052147  0.003279   
2         0.20  0.884058  0.695652  0.779762  0.274481  0.027607  0.000937   
3         0.15  0.985507  0.304348  0.148810  0.000000  0.009202  0.000000   
4         0.25  0.811594  0.434783  0.000000  0.537092  0.035276  0.034192   

        ISI       BUI       FWI  Temp_Humidity  Temp_Humidity_Ratio  \
0  0.068421  0.034380  0.016077       0.858544             0.774694   
1  0.052632  0.041854  0.012862       0.830823             0.794466   
2  0.015789  0.023916  0.003215       0.553647             0.767010   
3  0.000000  0.008969  0.000000       0.399696             0.767364   
4  0.063158  0.041854  0.016077       0.654163             0.766713   

   Heat_Index  
0    0.349570  
1    0.351719  
2    0.208812  
3    0.161

In [29]:
df_scaled.to_csv("forest_fire_scaled.csv", index=False)
print("Saved: forest_fire_scaled.csv")
print("Shape:", df_scaled.shape)
print("Columns:", df_scaled.columns.tolist())

Saved: forest_fire_scaled.csv
Shape: (243, 20)
Columns: ['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC', 'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Temp_Humidity', 'Temp_Humidity_Ratio', 'Heat_Index', 'Fire_Risk', 'Fire_Risk_Label', 'Fire_Risk_Encoded']


#### Model Training


In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score


In [31]:
print(df.columns)

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Temp_Humidity',
       'Temp_Humidity_Ratio', 'Heat_Index', 'Fire_Risk', 'Fire_Risk_Label',
       'Fire_Risk_Encoded'],
      dtype='object')


In [32]:
X = df.drop(columns=["Fire_Risk", "Fire_Risk_Label", "Fire_Risk_Encoded","Classes","FWI","day","month","year"])
y = df["Fire_Risk_Label"]

In [33]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42,stratify=y)

In [34]:
X_train

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,Temp_Humidity,Temp_Humidity_Ratio,Heat_Index
199,1.338944,-1.692242,-0.532446,-0.381657,1.149268,1.715732,0.785603,2.715506,1.352864,-2.265818,-0.791225,-8.906697
117,-0.318255,-0.543409,-1.601738,-0.381657,0.290334,-0.701892,-0.696503,-0.540898,-0.738816,0.172942,0.585664,-10.675621
202,1.062744,0.605425,-0.176015,-0.381657,0.569662,1.796589,1.422594,0.086262,1.733169,0.643412,1.755369,-9.102526
8,-1.975454,1.754259,-0.888877,-0.281611,-1.741776,-0.548264,-0.223490,-1.047449,-0.435980,-3.465457,-1.126091,-12.390549
68,-0.042055,-0.137938,0.893277,-0.231588,-0.051842,-0.273350,-0.051104,-0.613262,-0.182443,0.005801,0.304884,-10.352744
...,...,...,...,...,...,...,...,...,...,...,...,...
79,0.786544,-0.002781,1.249708,-0.381657,0.807091,0.688848,1.502481,1.195851,1.028900,-0.002187,-282.827319,-9.434932
41,-0.318255,0.875739,-0.888877,-0.331634,-0.191506,-0.548264,-0.456843,-0.782113,-0.527535,-0.278708,-0.363413,-10.608921
49,0.234145,0.199954,-0.176015,-0.331634,0.248435,-0.192493,0.266341,-0.468533,-0.013419,0.046818,1.170991,-10.033043
37,0.234145,0.402690,1.249708,-0.381657,0.541730,-0.176321,0.007760,0.303355,-0.090888,0.094288,0.581452,-10.023514


In [35]:
y_train

199    2
117    0
202    1
8      0
68     0
      ..
79     2
41     0
49     1
37     1
108    1
Name: Fire_Risk_Label, Length: 194, dtype: int64

In [36]:
rf_model = RandomForestClassifier(
n_estimators=200,
max_depth=10,
random_state=42
)

In [37]:
rf_model.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",200
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",10
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric(y

In [38]:
y_pred = rf_model.predict(X_test)

print("Predictions:")
print(y_pred)

Predictions:
[0 0 0 0 0 1 1 1 0 0 1 1 0 0 2 0 1 1 0 1 1 2 0 1 1 0 0 0 0 1 1 2 2 2 2 2 2
 1 0 2 2 1 0 1 0 0 1 2 0]


In [39]:
accuracy = accuracy_score(y_test, y_pred)
print()
print("Accuracy:", accuracy)


print("Confusion Matrix:")
print()
print(confusion_matrix(y_test, y_pred))


print("Classification Report:")
print()
print(classification_report(y_test, y_pred))


Accuracy: 0.9387755102040817
Confusion Matrix:

[[21  0  0]
 [ 0 16  2]
 [ 0  1  9]]
Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       0.94      0.89      0.91        18
           2       0.82      0.90      0.86        10

    accuracy                           0.94        49
   macro avg       0.92      0.93      0.92        49
weighted avg       0.94      0.94      0.94        49



#### Evaluation

In [40]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
sample = pd.DataFrame({
    'Temperature':        [1.89,   -0.87,   -1.97],
    'RH':                 [-1.28,   0.80,    1.82],
    'Ws':                 [-1.24,   0.18,    1.96],
    'Rain':               [-0.38,  -0.38,    1.91],
    'FFMC':               [0.96,   -0.14,   -2.57],
    'DMC':                [0.14,   -0.89,   -1.08],
    'DC':                 [-0.38,  -0.36,   -0.88],
    'ISI':                [1.17,   -0.63,   -1.11],
    'BUI':                [-0.02,  -0.78,   -1.05],
    'Temp_Humidity':      [-2.43,  -0.70,   -3.19],
    'Temp_Humidity_Ratio':[-1.46,  -1.07,   -1.22],
    'Heat_Index':         [-8.28,  -11.21,  -12.39],
})

label_map = {0: 'Low', 1: 'Moderate', 2: 'Severe'}

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

rf_model.fit(X_train, y_train)

predictions = rf_model.predict(sample)

print("Fire Risk Predictions")
for i, pred in enumerate(predictions):
    print(f"Sample {i+1}: {label_map[pred]}")

Fire Risk Predictions
Sample 1: Severe
Sample 2: Low
Sample 3: Low
